/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pvetec_demo2_JNIUtils */

#ifndef _Included_com_pvetec_demo2_JNIUtils
#define _Included_com_pvetec_demo2_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pvetec_demo2_JNIUtils
 * Method:    getPassWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pvetec_demo2_JNIUtils_getPassWord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
